### ISSUE TITLE
Disable debug

### ISSUE THREAD

**Issue by HaViGit** [tekk/TTGO-T-Beam-Car-Tracker#3]
First of all thanks for sharing this project! Maybe you can assist me with disabling debugging the sketch. When I comment (//) the line:

#define DEBUG 1 // for real use comment this out

an error is generated saying #elif with no expression. Can you tell me how to disable debugging when using the tracker for real?

**Comment by tekk** [comment]
Hi. First of all, all the DEBUG code stayed there only as a residue of code changes that I've done in the past. When I was developing this, there has been numerous sections that were for debugging purposes only. As the code evolved, I deleted most of them. Looking at the code I see that when DEBUG is defined, LORA TX is scheduled every 120 seconds and otherwise it's 480 seconds.

So you should be good to go with:
`#define DEBUG 1` - for 480 sec. interval between GPS packets
or
`#define DEBUG 0` - for 120 sec. between packets
I see that it's in exact opposite logic as it should be, my fault.

Or you can remove:
`#define DEBUG 1`
and
```
#ifdef DEBUG
const unsigned int TX_INTERVAL = 480;
#elif
const unsigned int TX_INTERVAL = 120;
#endif
```
and replace with 
`const unsigned int TX_INTERVAL = 480;` (change to any number that fits your scenario).

Hope it helps.

**Comment by HaViGit** [comment]
Hi Peter,

Thanks for your fast reply and solution!

Best regards, Hans.

**Comment by HaViGit** [comment]
Solved and issue closed, thanks!
